"use client";

import Link from "next/link";
import {useEffect,useMemo,useState} from "react";

type Lead={id:string;name:string;phone:string;email?:string;project_type:string;message:string;status:"new"|"contacted"|"qualified"|"closed"|"spam";created_at:string};
type Post={id:string;slug:string;title:string;excerpt:string;content:string;category:string;cover_url?:string|null;is_published:boolean;published_at?:string|null;created_at:string};
type PostDraft={id?:string;slug:string;title:string;excerpt:string;content:string;category:string;coverUrl:string;isPublished:boolean};
type Filter="all"|Lead["status"];
type Section="requests"|"posts";
const API=process.env.NEXT_PUBLIC_API_URL||"http://localhost:4000/api";
const statusLabels:Record<Lead["status"],string>={new:"جدید",contacted:"تماس گرفته شد",qualified:"مناسب",closed:"بسته‌شده",spam:"اسپم"};
const emptyPost:PostDraft={slug:"",title:"",excerpt:"",content:"",category:"طراحی سایت",coverUrl:"",isPublished:false};

export default function AdminPage(){
 const [token,setToken]=useState("");const [leads,setLeads]=useState<Lead[]>([]);const [posts,setPosts]=useState<Post[]>([]);const [section,setSection]=useState<Section>("requests");const [draft,setDraft]=useState<PostDraft|null>(null);const [error,setError]=useState("");const [notice,setNotice]=useState("");const [loading,setLoading]=useState(false);const [saving,setSaving]=useState(false);const [filter,setFilter]=useState<Filter>("all");const [search,setSearch]=useState("");const [menuOpen,setMenuOpen]=useState(false);const [showPass,setShowPass]=useState(false);
 useEffect(()=>{const saved=localStorage.getItem("websaz_admin_token");if(saved){setToken(saved);void loadAll(saved)}},[]);
 async function authFetch(path:string,auth=token,init?:RequestInit){const response=await fetch(`${API}${path}`,{...init,headers:{...(init?.body?{"Content-Type":"application/json"}:{}),...init?.headers,Authorization:`Bearer ${auth}`},signal:AbortSignal.timeout(10000)});if(response.status===401){logout();throw new Error("UNAUTHORIZED")}return response}
 async function loadAll(auth=token){setLoading(true);setError("");try{const [leadResponse,postResponse]=await Promise.all([authFetch("/admin/leads",auth),authFetch("/admin/posts",auth)]);if(!leadResponse.ok||!postResponse.ok)throw new Error();setLeads((await leadResponse.json()).data);setPosts((await postResponse.json()).data)}catch(e){if((e as Error).message!=="UNAUTHORIZED")setError("ارتباط با سرور یا پایگاه داده برقرار نیست.")}finally{setLoading(false)}}
 async function login(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setLoading(true);setError("");const data=new FormData(event.currentTarget);try{const response=await fetch(`${API}/admin/login`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:data.get("email"),password:data.get("password")}),signal:AbortSignal.timeout(8000)});if(!response.ok){setError("ایمیل یا رمز عبور صحیح نیست.");return}const body=await response.json();localStorage.setItem("websaz_admin_token",body.token);setToken(body.token);void loadAll(body.token)}catch{setError("اتصال به سرور ممکن نیست؛ وضعیت بک‌اند را بررسی کنید.")}finally{setLoading(false)}}
 async function changeLead(id:string,status:Lead["status"]){setLeads(current=>current.map(item=>item.id===id?{...item,status}:item));try{const response=await authFetch(`/admin/leads/${id}`,token,{method:"PATCH",body:JSON.stringify({status})});if(!response.ok)throw new Error()}catch{setError("تغییر وضعیت ذخیره نشد.");void loadAll()}}
 async function savePost(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(!draft)return;setSaving(true);setError("");setNotice("");try{const response=await authFetch(draft.id?`/admin/posts/${draft.id}`:"/admin/posts",token,{method:draft.id?"PUT":"POST",body:JSON.stringify(draft)});if(!response.ok){const body=await response.json().catch(()=>null);throw new Error(body?.error==="VALIDATION_ERROR"?"اطلاعات مقاله کامل یا معتبر نیست.":"ذخیره مقاله انجام نشد.")}setNotice(draft.isPublished?"مقاله ذخیره و منتشر شد. نمایش تغییرات در سایت ممکن است تا یک دقیقه زمان ببرد.":"پیش‌نویس مقاله ذخیره شد.");setDraft(null);await loadAll()}catch(e){setError((e as Error).message||"ذخیره مقاله انجام نشد.")}finally{setSaving(false)}}
 async function removePost(post:Post){if(!window.confirm(`مقاله «${post.title}» حذف شود؟ این عملیات قابل بازگشت نیست.`))return;setError("");try{const response=await authFetch(`/admin/posts/${post.id}`,token,{method:"DELETE"});if(!response.ok)throw new Error();setPosts(current=>current.filter(item=>item.id!==post.id));setNotice("مقاله حذف شد.")}catch{setError("حذف مقاله انجام نشد.")}}
 function editPost(post:Post){setDraft({id:post.id,slug:post.slug,title:post.title,excerpt:post.excerpt,content:post.content,category:post.category,coverUrl:post.cover_url||"",isPublished:post.is_published});setSection("posts");window.scrollTo({top:0,behavior:"smooth"})}
 function logout(){localStorage.removeItem("websaz_admin_token");setToken("");setLeads([]);setPosts([])}
 const visible=useMemo(()=>leads.filter(item=>(filter==="all"||item.status===filter)&&(!search||`${item.name} ${item.phone} ${item.email||""} ${item.project_type}`.toLowerCase().includes(search.toLowerCase()))),[leads,filter,search]);
 const counts=useMemo(()=>({all:leads.length,new:leads.filter(x=>x.status==="new").length,contacted:leads.filter(x=>x.status==="contacted").length,qualified:leads.filter(x=>x.status==="qualified").length,closed:leads.filter(x=>x.status==="closed").length,spam:leads.filter(x=>x.status==="spam").length}),[leads]);
 if(!token)return <Login loading={loading} error={error} showPass={showPass} setShowPass={setShowPass} submit={login}/>;
 return <div className={`dashboard ${menuOpen?"menu-open":""}`}>
   <button className="admin-scrim" aria-label="بستن منو" onClick={()=>setMenuOpen(false)}/>
   <aside className="admin-sidebar"><div className="admin-logo"><i>◇</i><span>وب‌ساز<small>پنل مدیریت</small></span></div><nav><button className={section==="requests"?"active":""} onClick={()=>{setSection("requests");setMenuOpen(false)}}><span>◦</span>درخواست‌ها<em>{counts.new}</em></button><button className={section==="posts"?"active":""} onClick={()=>{setSection("posts");setMenuOpen(false)}}><span>▤</span>مدیریت بلاگ<em>{posts.length}</em></button><Link href="/" target="_blank"><span>↗</span>مشاهده سایت</Link></nav><div className="admin-help"><b>{section==="posts"?"مدیریت محتوا":"پیگیری درخواست‌ها"}</b><p>{section==="posts"?"مقاله‌ها را به‌صورت پیش‌نویس ذخیره کنید و پس از بازبینی منتشر کنید.":"درخواست‌های جدید را بررسی و وضعیت پیگیری را ثبت کنید."}</p></div><div className="admin-user"><span>م</span><div><b>مدیر وب‌ساز</b><small>دسترسی مدیریت سایت</small></div><button onClick={logout} title="خروج">↪</button></div></aside>
   <main className="admin-content"><header className="admin-top"><button className="admin-menu" onClick={()=>setMenuOpen(true)} aria-label="بازکردن منو">☰</button><div><h1>{section==="posts"?"مدیریت بلاگ":"مدیریت درخواست‌ها"}</h1><p>{section==="posts"?"نوشته‌های سایت را ایجاد، ویرایش و منتشر کنید.":"آخرین وضعیت درخواست‌های مشاوره را بررسی کنید."}</p></div><div className="admin-top-actions"><button className="refresh" onClick={()=>loadAll()} disabled={loading}>↻ <span>به‌روزرسانی</span></button><div className="admin-avatar">م</div></div></header>
     {error&&<div className="admin-alert global"><span>!</span>{error}<button onClick={()=>setError("")}>بستن</button></div>}{notice&&<div className="admin-notice">✓ {notice}<button onClick={()=>setNotice("")}>×</button></div>}
     {section==="requests"?<RequestsView leads={visible} counts={counts} filter={filter} setFilter={setFilter} search={search} setSearch={setSearch} loading={loading} change={changeLead}/>:<PostsView posts={posts} loading={loading} draft={draft} setDraft={setDraft} save={savePost} edit={editPost} remove={removePost} saving={saving}/>}<p className="admin-copy">وب‌ساز · پنل مدیریت سایت</p>
   </main>
 </div>
}

function RequestsView({leads,counts,filter,setFilter,search,setSearch,loading,change}:{leads:Lead[];counts:Record<Filter,number>;filter:Filter;setFilter:(v:Filter)=>void;search:string;setSearch:(v:string)=>void;loading:boolean;change:(id:string,status:Lead["status"])=>void}){return <><section className="admin-stats" id="overview"><Stat icon="✦" tone="blue" value={counts.new} label="درخواست جدید" hint="نیازمند بررسی"/><Stat icon="☎" tone="purple" value={counts.contacted} label="تماس گرفته‌شده" hint="در حال پیگیری"/><Stat icon="✓" tone="green" value={counts.qualified} label="مشتری مناسب" hint="فرصت همکاری"/><Stat icon="◎" tone="orange" value={counts.all} label="کل درخواست‌ها" hint="از ابتدای ثبت"/></section><section className="admin-card"><div className="admin-card-head"><div><h2>درخواست‌های مشاوره</h2><p>اطلاعات تماس و مرحله پیگیری مشتریان</p></div><label className="admin-search"><span>⌕</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="جست‌وجوی نام، شماره یا نوع پروژه..."/></label></div><div className="admin-filters">{(["all","new","contacted","qualified","closed"] as Filter[]).map(key=><button key={key} className={filter===key?"active":""} onClick={()=>setFilter(key)}>{key==="all"?"همه":statusLabels[key as Lead["status"]]}<span>{counts[key]}</span></button>)}</div>{loading&&!leads.length?<Loading/>:leads.length?<div className="lead-list">{leads.map(item=><LeadCard key={item.id} item={item} change={change}/>)}</div>:<Empty title="درخواستی پیدا نشد" text="فیلتر یا عبارت جست‌وجو را تغییر دهید."/>}</section></>}

function PostsView({posts,loading,draft,setDraft,save,edit,remove,saving}:{posts:Post[];loading:boolean;draft:PostDraft|null;setDraft:(v:PostDraft|null)=>void;save:(e:React.FormEvent<HTMLFormElement>)=>void;edit:(p:Post)=>void;remove:(p:Post)=>void;saving:boolean}){if(draft)return <PostEditor draft={draft} setDraft={setDraft} save={save} saving={saving}/>;return <section className="admin-card admin-posts"><div className="admin-card-head"><div><h2>نوشته‌های بلاگ</h2><p>{posts.filter(x=>x.is_published).length.toLocaleString("fa-IR")} مقاله منتشرشده و {posts.filter(x=>!x.is_published).length.toLocaleString("fa-IR")} پیش‌نویس</p></div><button className="btn primary new-post" onClick={()=>setDraft({...emptyPost})}>نوشتن مقاله جدید</button></div>{loading&&!posts.length?<Loading/>:posts.length?<div className="post-admin-list">{posts.map(post=><article key={post.id}><div className="post-admin-icon">{post.category.charAt(0)}</div><div className="post-admin-info"><div><span className={post.is_published?"published":"draft"}>{post.is_published?"منتشرشده":"پیش‌نویس"}</span><small>{post.category}</small></div><h3>{post.title}</h3><p>{post.excerpt}</p></div><div className="post-admin-date"><span>{post.published_at?new Date(post.published_at).toLocaleDateString("fa-IR"):"بدون تاریخ انتشار"}</span><Link href={`/blog/${post.slug}`} target="_blank">مشاهده</Link></div><div className="post-admin-actions"><button onClick={()=>edit(post)}>ویرایش</button><button className="danger" onClick={()=>remove(post)}>حذف</button></div></article>)}</div>:<Empty title="هنوز مقاله‌ای ندارید" text="نخستین نوشته بلاگ را ایجاد و منتشر کنید."/>}</section>}

function PostEditor({draft,setDraft,save,saving}:{draft:PostDraft;setDraft:(v:PostDraft|null)=>void;save:(e:React.FormEvent<HTMLFormElement>)=>void;saving:boolean}){const update=<K extends keyof PostDraft>(key:K,value:PostDraft[K])=>setDraft({...draft,[key]:value});return <form className="admin-card post-editor" onSubmit={save}><div className="post-editor-head"><div><span>{draft.id?"ویرایش نوشته":"نوشته جدید"}</span><h2>{draft.id?draft.title||"ویرایش مقاله":"ایجاد مقاله برای بلاگ"}</h2></div><button type="button" onClick={()=>setDraft(null)}>بازگشت به فهرست</button></div><div className="post-editor-grid"><div className="post-editor-main"><label>عنوان مقاله<input required minLength={5} maxLength={180} value={draft.title} onChange={e=>update("title",e.target.value)} placeholder="یک عنوان روشن و مشخص بنویسید"/></label><label>خلاصه مقاله<textarea required minLength={20} maxLength={500} rows={3} value={draft.excerpt} onChange={e=>update("excerpt",e.target.value)} placeholder="خلاصه‌ای که در صفحه فهرست نمایش داده می‌شود"/></label><label>متن مقاله<textarea className="content-input" required minLength={50} maxLength={30000} rows={15} value={draft.content} onChange={e=>update("content",e.target.value)} placeholder="متن را بنویسید. برای شروع پاراگراف تازه، یک خط خالی ایجاد کنید."/></label></div><aside className="post-editor-side"><label>نامک انگلیسی<input dir="ltr" required pattern="[a-z0-9]+(?:-[a-z0-9]+)*" value={draft.slug} onChange={e=>update("slug",e.target.value.toLowerCase().replace(/\s+/g,"-"))} placeholder="website-design-guide"/><small>فقط حروف انگلیسی کوچک، عدد و خط تیره</small></label><label>دسته‌بندی<input required minLength={2} value={draft.category} onChange={e=>update("category",e.target.value)} placeholder="طراحی سایت"/></label><label>نشانی تصویر شاخص <small>اختیاری</small><input dir="ltr" type="url" value={draft.coverUrl} onChange={e=>update("coverUrl",e.target.value)} placeholder="https://..."/></label><label className="publish-switch"><input type="checkbox" checked={draft.isPublished} onChange={e=>update("isPublished",e.target.checked)}/><span></span><div><b>انتشار در سایت</b><small>{draft.isPublished?"پس از ذخیره برای همه نمایش داده می‌شود.":"به‌صورت پیش‌نویس ذخیره می‌شود."}</small></div></label><button className="btn primary" disabled={saving}>{saving?"در حال ذخیره…":draft.isPublished?"ذخیره و انتشار":"ذخیره پیش‌نویس"}</button></aside></div></form>}

function Login({loading,error,showPass,setShowPass,submit}:{loading:boolean;error:string;showPass:boolean;setShowPass:(v:boolean)=>void;submit:(e:React.FormEvent<HTMLFormElement>)=>void}){return <main className="admin-shell"><section className="login-showcase"><div className="login-brand"><i>◇</i> وب‌ساز</div><div><span className="login-chip">پنل یکپارچه مدیریت</span><h1>درخواست‌ها و محتوای سایت،<br/>مرتب و در دسترس.</h1><p>سرنخ‌های فروش را پیگیری کنید و نوشته‌های بلاگ را بدون مراجعه به کد ایجاد یا به‌روزرسانی کنید.</p><div className="login-points"><span>✓ مدیریت درخواست‌ها</span><span>✓ انتشار و ویرایش مقاله</span><span>✓ مناسب موبایل و دسکتاپ</span></div></div><small>© ۱۴۰۵ وب‌ساز</small></section><section className="login-form-wrap"><form className="admin-login" onSubmit={submit}><div className="login-mobile-brand"><i>◇</i> وب‌ساز</div><span className="login-kicker">ورود امن مدیر</span><h2>خوش برگشتید</h2><p>برای ورود، اطلاعات حساب مدیریت را وارد کنید.</p><label>آدرس ایمیل<div className="login-input"><span>@</span><input name="email" type="email" required placeholder="admin@websaz.ir" autoComplete="username"/></div></label><label>رمز عبور<div className="login-input"><span>●</span><input name="password" type={showPass?"text":"password"} required placeholder="رمز عبور" autoComplete="current-password"/><button type="button" onClick={()=>setShowPass(!showPass)}>{showPass?"پنهان":"نمایش"}</button></div></label><button className="btn primary login-submit" disabled={loading}>{loading?"در حال بررسی…":"ورود به پنل"}<b>←</b></button>{error&&<div className="login-error">! {error}</div>}<Link href="/">بازگشت به سایت</Link></form></section></main>}
function Stat({icon,tone,value,label,hint}:{icon:string;tone:string;value:number;label:string;hint:string}){return <article className={`stat ${tone}`}><div className="stat-icon">{icon}</div><div><strong>{value.toLocaleString("fa-IR")}</strong><b>{label}</b><small>{hint}</small></div></article>}
function LeadCard({item,change}:{item:Lead;change:(id:string,status:Lead["status"])=>void}){return <article className="lead-card"><div className="lead-person"><span>{item.name.charAt(0)}</span><div><b>{item.name}</b><small>{new Date(item.created_at).toLocaleDateString("fa-IR",{year:"numeric",month:"long",day:"numeric"})}</small></div></div><div className="lead-contact"><a href={`tel:${item.phone}`}>☎ {item.phone}</a>{item.email&&<a href={`mailto:${item.email}`}>@ {item.email}</a>}<span>◦ {item.project_type}</span></div><p>{item.message}</p><div className="lead-action"><label>وضعیت پیگیری<select className={`status-${item.status}`} value={item.status} onChange={e=>change(item.id,e.target.value as Lead["status"])}>{Object.entries(statusLabels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><div><a href={`tel:${item.phone}`}>تماس</a>{item.email&&<a href={`mailto:${item.email}`}>ارسال ایمیل</a>}</div></div></article>}
function Loading(){return <div className="admin-loading"><i/><i/><i/></div>}
function Empty({title,text}:{title:string;text:string}){return <div className="admin-empty"><span>⌕</span><h3>{title}</h3><p>{text}</p></div>}
