"use client";

import Link from "next/link";
import {useEffect,useMemo,useState} from "react";

type Lead={id:string;name:string;phone:string;email?:string;project_type:string;message:string;status:"new"|"contacted"|"qualified"|"closed"|"spam";created_at:string};
type Filter="all"|Lead["status"];
const API=process.env.NEXT_PUBLIC_API_URL||"http://localhost:4000/api";
const statusLabels:Record<Lead["status"],string>={new:"جدید",contacted:"تماس گرفته شد",qualified:"مناسب",closed:"بسته‌شده",spam:"اسپم"};

export default function AdminPage(){
 const [token,setToken]=useState(""); const [leads,setLeads]=useState<Lead[]>([]); const [error,setError]=useState(""); const [loading,setLoading]=useState(false); const [filter,setFilter]=useState<Filter>("all"); const [search,setSearch]=useState(""); const [menuOpen,setMenuOpen]=useState(false); const [showPass,setShowPass]=useState(false);
 useEffect(()=>{const saved=localStorage.getItem("websaz_admin_token");if(saved){setToken(saved);void load(saved)}},[]);
 async function load(auth=token){setLoading(true);setError("");try{const response=await fetch(`${API}/admin/leads`,{headers:{Authorization:`Bearer ${auth}`},signal:AbortSignal.timeout(8000)});if(response.status===401){logout();return}if(!response.ok)throw new Error();setLeads((await response.json()).data)}catch{setError("ارتباط با سرور یا پایگاه داده برقرار نیست.")}finally{setLoading(false)}}
 async function login(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setLoading(true);setError("");const data=new FormData(event.currentTarget);try{const response=await fetch(`${API}/admin/login`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:data.get("email"),password:data.get("password")}),signal:AbortSignal.timeout(8000)});if(!response.ok){setError("ایمیل یا رمز عبور صحیح نیست.");return}const body=await response.json();localStorage.setItem("websaz_admin_token",body.token);setToken(body.token);void load(body.token)}catch{setError("اتصال به سرور ممکن نیست؛ وضعیت بک‌اند را بررسی کنید.")}finally{setLoading(false)}}
 async function change(id:string,status:Lead["status"]){setLeads(current=>current.map(item=>item.id===id?{...item,status}:item));try{const response=await fetch(`${API}/admin/leads/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`},body:JSON.stringify({status})});if(!response.ok)throw new Error()}catch{setError("تغییر وضعیت ذخیره نشد.");void load()}}
 function logout(){localStorage.removeItem("websaz_admin_token");setToken("");setLeads([])}
 const visible=useMemo(()=>leads.filter(item=>(filter==="all"||item.status===filter)&&(!search||`${item.name} ${item.phone} ${item.email||""} ${item.project_type}`.toLowerCase().includes(search.toLowerCase()))),[leads,filter,search]);
 const counts=useMemo(()=>({all:leads.length,new:leads.filter(x=>x.status==="new").length,contacted:leads.filter(x=>x.status==="contacted").length,qualified:leads.filter(x=>x.status==="qualified").length,closed:leads.filter(x=>x.status==="closed").length,spam:leads.filter(x=>x.status==="spam").length}),[leads]);
 if(!token)return <Login loading={loading} error={error} showPass={showPass} setShowPass={setShowPass} submit={login}/>;
 return <div className={`dashboard ${menuOpen?"menu-open":""}`}>
   <button className="admin-scrim" aria-label="بستن منو" onClick={()=>setMenuOpen(false)}/>
   <aside className="admin-sidebar"><div className="admin-logo"><i>◇</i><span>وب‌ساز<small>پنل مدیریت</small></span></div><nav><a className="active" href="#requests"><span>▦</span>درخواست‌ها<em>{counts.new}</em></a><a href="#overview"><span>⌁</span>نمای کلی</a><Link href="/" target="_blank"><span>↗</span>مشاهده سایت</Link></nav><div className="admin-help"><b>راهنمای سریع</b><p>درخواست‌های جدید را بررسی و وضعیت پیگیری را ثبت کنید.</p></div><div className="admin-user"><span>م</span><div><b>مدیر وب‌ساز</b><small>admin@example.com</small></div><button onClick={logout} title="خروج">↪</button></div></aside>
   <main className="admin-content"><header className="admin-top"><button className="admin-menu" onClick={()=>setMenuOpen(true)} aria-label="بازکردن منو">☰</button><div><h1>سلام، خوش آمدید 👋</h1><p>آخرین وضعیت درخواست‌های مشاوره را اینجا ببینید.</p></div><div className="admin-top-actions"><button className="refresh" onClick={()=>load()} disabled={loading}>↻ <span>به‌روزرسانی</span></button><div className="admin-avatar">م</div></div></header>
     <section className="admin-stats" id="overview"><Stat icon="✦" tone="blue" value={counts.new} label="درخواست جدید" hint="نیازمند بررسی"/><Stat icon="☎" tone="purple" value={counts.contacted} label="تماس گرفته‌شده" hint="در حال پیگیری"/><Stat icon="✓" tone="green" value={counts.qualified} label="مشتری مناسب" hint="فرصت همکاری"/><Stat icon="◎" tone="orange" value={counts.all} label="کل درخواست‌ها" hint="از ابتدای ثبت"/></section>
     <section className="admin-card" id="requests"><div className="admin-card-head"><div><h2>درخواست‌های مشاوره</h2><p>اطلاعات تماس و مرحله پیگیری مشتریان</p></div><label className="admin-search"><span>⌕</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="جست‌وجوی نام، شماره یا نوع پروژه..."/></label></div><div className="admin-filters">{(["all","new","contacted","qualified","closed"] as Filter[]).map(key=><button key={key} className={filter===key?"active":""} onClick={()=>setFilter(key)}>{key==="all"?"همه":statusLabels[key as Lead["status"]]}<span>{counts[key]}</span></button>)}</div>
       {error&&<div className="admin-alert"><span>!</span>{error}<button onClick={()=>load()}>تلاش دوباره</button></div>}
       {loading&&!leads.length?<div className="admin-loading"><i/><i/><i/></div>:visible.length?<div className="lead-list">{visible.map(item=><LeadCard key={item.id} item={item} change={change}/>)}</div>:<div className="admin-empty"><span>⌕</span><h3>درخواستی پیدا نشد</h3><p>فیلتر یا عبارت جست‌وجو را تغییر دهید.</p></div>}
     </section><p className="admin-copy">وب‌ساز · پنل مدیریت درخواست‌ها</p>
   </main>
 </div>
}

function Login({loading,error,showPass,setShowPass,submit}:{loading:boolean;error:string;showPass:boolean;setShowPass:(v:boolean)=>void;submit:(e:React.FormEvent<HTMLFormElement>)=>void}){return <main className="admin-shell"><section className="login-showcase"><div className="login-brand"><i>◇</i> وب‌ساز</div><div><span className="login-chip">پنل یکپارچه مدیریت</span><h1>درخواست‌های مشتریان،<br/>مرتب و همیشه در دسترس.</h1><p>سرنخ‌ها را بررسی کنید، مراحل پیگیری را ثبت کنید و هیچ فرصت همکاری را از دست ندهید.</p><div className="login-points"><span>✓ مدیریت سریع درخواست‌ها</span><span>✓ دسترسی امن مدیر</span><span>✓ مناسب موبایل و دسکتاپ</span></div></div><small>© ۱۴۰۵ وب‌ساز</small></section><section className="login-form-wrap"><form className="admin-login" onSubmit={submit}><div className="login-mobile-brand"><i>◇</i> وب‌ساز</div><span className="login-kicker">ورود امن مدیر</span><h2>خوش برگشتید</h2><p>برای ورود، اطلاعات حساب مدیریت را وارد کنید.</p><label>آدرس ایمیل<div className="login-input"><span>@</span><input name="email" type="email" required placeholder="admin@example.com" autoComplete="username"/></div></label><label>رمز عبور<div className="login-input"><span>●</span><input name="password" type={showPass?"text":"password"} required placeholder="رمز عبور" autoComplete="current-password"/><button type="button" onClick={()=>setShowPass(!showPass)}>{showPass?"پنهان":"نمایش"}</button></div></label><div className="login-meta"><label><input type="checkbox"/> مرا به خاطر بسپار</label><span>دسترسی فقط برای مدیر سایت</span></div><button className="btn primary login-submit" disabled={loading}>{loading?"در حال بررسی…":"ورود به پنل"}<b>←</b></button>{error&&<div className="login-error">! {error}</div>}<Link href="/">بازگشت به سایت</Link></form></section></main>}
function Stat({icon,tone,value,label,hint}:{icon:string;tone:string;value:number;label:string;hint:string}){return <article className={`stat ${tone}`}><div className="stat-icon">{icon}</div><div><strong>{value.toLocaleString("fa-IR")}</strong><b>{label}</b><small>{hint}</small></div></article>}
function LeadCard({item,change}:{item:Lead;change:(id:string,status:Lead["status"])=>void}){return <article className="lead-card"><div className="lead-person"><span>{item.name.charAt(0)}</span><div><b>{item.name}</b><small>{new Date(item.created_at).toLocaleDateString("fa-IR",{year:"numeric",month:"long",day:"numeric"})}</small></div></div><div className="lead-contact"><a href={`tel:${item.phone}`}>☎ {item.phone}</a>{item.email&&<a href={`mailto:${item.email}`}>@ {item.email}</a>}<span>▦ {item.project_type}</span></div><p>{item.message}</p><div className="lead-action"><label>وضعیت پیگیری<select className={`status-${item.status}`} value={item.status} onChange={e=>change(item.id,e.target.value as Lead["status"])}>{Object.entries(statusLabels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><div><a href={`tel:${item.phone}`}>تماس</a>{item.email&&<a href={`mailto:${item.email}`}>ارسال ایمیل</a>}</div></div></article>}
