import Link from "next/link";
import { Footer, Header, Icon, Mockup, SectionTitle } from "./components";
import { faqs, portfolio, services, testimonials } from "./data";
import { getCollection } from "../lib/api";

export default async function Home() {
  const [liveServices,livePortfolio,liveTestimonials,liveFaqs]=await Promise.all([getCollection("services",services),getCollection("projects",portfolio),getCollection("testimonials",testimonials),getCollection("faqs",faqs)]);
  return <><Header /><main>
    <section className="hero hero-revamp"><div className="hero-grid-pattern"></div><div className="container hero-grid">
      <div className="hero-copy"><div className="hero-label"><i></i> شریک دیجیتال کسب‌وکارهای رو‌به‌رشد</div><h1>طراحی وب‌سایت،<br/><span>برای ساختن یک برند ماندگار.</span></h1><p>از ایده تا اجرا، وب‌سایتی سریع، زیبا و هدفمند می‌سازیم که اعتماد ایجاد کند و بازدیدکننده را به مشتری تبدیل کند.</p><div className="actions"><Link className="btn primary hero-primary" href="/contact">شروع یک پروژه <span>←</span></Link><Link className="btn secondary hero-secondary" href="/portfolio"><i>▶</i> مشاهده نمونه‌کارها</Link></div><div className="hero-proof"><div className="proof-avatars"><i>م</i><i>ن</i><i>ع</i><i>+</i></div><div><b>بیش از ۱۵۰ کسب‌وکار</b><span>به تجربه همکاری با ما اعتماد کرده‌اند</span></div><strong>★★★★★ <small>۴.۹ از ۵</small></strong></div></div>
      <div className="hero-visual"><div className="visual-glow"></div><div className="visual-top"><span><i></i> پروژه فعال</span><b>طراحی اختصاصی، بدون قالب آماده</b></div><Mockup/><div className="visual-metric"><span>↗</span><div><b>۴۲٪</b><small>رشد نرخ تبدیل</small></div></div><div className="visual-speed"><b>۹۶</b><span>سرعت و عملکرد</span></div></div>
    </div><div className="container hero-strip"><span>طراحی هدفمند</span><i></i><span>توسعه استاندارد</span><i></i><span>سئوی تکنیکال</span><i></i><span>پشتیبانی واقعی</span></div></section>

    <section className="metrics-wrap container"><div className="metrics-panel"><div className="metrics-intro"><span>تجربه‌ای که می‌شود اندازه گرفت</span><h2>نتیجه، مهم‌تر از ظاهر است.</h2><p>هر عدد، حاصل یک همکاری موفق و یک مسئله حل‌شده است.</p></div><div className="metrics-list"><article><div><strong>۲۰۰</strong><em>+</em></div><b>پروژه موفق</b><span>در صنایع مختلف</span></article><article><div><strong>۱۵۰</strong><em>+</em></div><b>مشتری همراه</b><span>از استارتاپ تا سازمان</span></article><article><div><strong>۹۸</strong><em>٪</em></div><b>رضایت مشتریان</b><span>براساس بازخورد پروژه‌ها</span></article><article><div><strong>۸</strong><em>سال</em></div><b>تجربه تخصصی</b><span>در طراحی و توسعه وب</span></article></div></div><div className="client-line"><span>اعتماد برندهایی که کیفیت برایشان مهم است</span><div><b>digikala</b><b>Snapp!</b><b>همراه اول</b><b>ماموت</b><b>علی‌بابا</b></div></div></section>

    <section className="section container"><SectionTitle kicker="خدمات ما" title="تمامی خدمات طراحی سایت در یکجا" text="از طراحی رابط کاربری تا توسعه اختصاصی، کنار شما هستیم."/><div className="service-grid">{liveServices.map((s)=><article className="service-card" key={s.slug}><Icon value={s.icon}/><h3>{s.title}</h3><p>{s.short}</p><Link href={`/services#${s.slug}`}>مشاهده جزئیات ←</Link></article>)}</div></section>

    <section className="section pale"><div className="container split"><div className="feature-visual"><Mockup compact/><span className="float-card fc1">۹۸٪ رضایت مشتریان</span><span className="float-card fc2">رشد پایدار کسب‌وکار</span></div><div><SectionTitle align="right" kicker="چرا وب‌ساز؟" title="تفاوت ما در جزئیات است" text="ما فقط یک سایت تحویل نمی‌دهیم؛ یک ابزار قدرتمند برای رشد کسب‌وکار شما می‌سازیم."/><div className="feature-list">{["طراحی اختصاصی متناسب با برند","سرعت و امنیت بالا","سئوی تکنیکال از روز اول","تجربه کاربری هدفمند","کدنویسی تمیز و مقیاس‌پذیر","پشتیبانی شفاف و متعهدانه"].map((x,i)=><div key={x}><Icon value={["✦","⚡","⌁","◎","</>","♡"][i]}/><span>{x}</span></div>)}</div></div></div></section>

    <section className="section container"><SectionTitle kicker="فرآیند کار" title="از ایده تا موفقیت، در ۵ مرحله" text="هر مرحله شفاف، قابل پیگیری و با تأیید شما انجام می‌شود."/><div className="steps">{["مشاوره و تحلیل","طراحی وایرفریم","طراحی UI/UX","توسعه و پیاده‌سازی","تحویل و پشتیبانی"].map((x,i)=><div key={x}><span>{i+1}</span><b>{x}</b><small>{["شناخت اهداف و مخاطبان","ساخت مسیر و ساختار صفحات","خلق ظاهر اختصاصی برند","کدنویسی سریع و استاندارد","آموزش، انتشار و همراهی"][i]}</small></div>)}</div></section>

    <section className="section work-section projects-polished"><div className="container"><div className="projects-heading"><SectionTitle align="right" kicker="نمونه‌کارهای منتخب" title="پروژه‌هایی که نتیجه ساخته‌اند" text="هر پروژه ترکیبی از استراتژی، طراحی دقیق و اجرای استاندارد است."/><Link className="projects-all" href="/portfolio">مشاهده همه پروژه‌ها <span>←</span></Link></div><div className="project-showcase">{livePortfolio.slice(0,4).map((p,i)=><Link href={`/portfolio/${p.slug}`} className={`project-tile project-${i+1} ${i===0?"featured":""}`} key={p.slug}><div className="project-preview"><div className="preview-top"><span/><span/><span/><b>{p.category}</b></div><div className="preview-layout"><aside><i/><i/><i/><i/></aside><div><span className="preview-label">{p.category}</span><strong>{p.title}</strong><p>تجربه‌ای ساده، سریع و هدفمند</p><button>مشاهده پروژه</button></div><section><i/><i/><i/></section></div></div><div className="project-caption"><div><span>۰{i+1}</span><h3>{p.title}</h3><p>{p.category}</p></div><strong>{p.result||"طراحی و توسعه اختصاصی"}</strong><i>←</i></div></Link>)}</div></div></section>

    <section className="section container"><SectionTitle kicker="نظرات مشتریان" title="آنچه مشتریان ما می‌گویند" text="اعتماد شما، ارزشمندترین سرمایه ماست."/><div className="testimonial-grid">{liveTestimonials.map(t=><figure key={t.name}><div className="stars">★★★★★</div><blockquote>«{t.text}»</blockquote><figcaption><span>{t.name.charAt(0)}</span><div><b>{t.name}</b><small>{t.role}</small></div></figcaption></figure>)}</div></section>

    <section className="section faq-wrap"><div className="container faq-grid"><div><span className="eyebrow">سؤالات متداول</span><h2>پاسخ به پرسش‌های شما</h2><p>اگر پاسخ پرسش خود را پیدا نکردید، با ما تماس بگیرید.</p><Link className="text-link" href="/contact">گفت‌وگو با مشاور ←</Link></div><div>{liveFaqs.slice(0,5).map((f,i)=><details key={f.q} open={i===0}><summary>{f.q}<span>+</span></summary><p>{f.a}</p></details>)}</div></div></section>
    <section className="cta"><div className="container"><span>شروع یک همکاری موفق</span><h2>آماده‌اید کسب‌وکارتان را حرفه‌ای‌تر کنید؟</h2><p>اولین قدم را با یک جلسه مشاوره رایگان و بدون تعهد بردارید.</p><div className="actions"><Link className="btn light" href="/contact">درخواست مشاوره رایگان</Link><a className="btn ghost" href="tel:+982191000000">۰۲۱-۹۱۰۰۰۰۰۰</a></div></div></section>
  </main><Footer /></>;
}
