import type {Metadata} from "next";
import Link from "next/link";
import {notFound} from "next/navigation";
import {Footer,Header,PageHero} from "../../components";
import {absoluteUrl,pageMetadata} from "../../../lib/seo";
import {servicePages,type ServiceSlug} from "../service-data";
export function generateStaticParams(){return Object.keys(servicePages).map(service=>({service}))}
const related:Record<ServiceSlug,ServiceSlug[]>={"corporate-website":["ui-ux","custom-website","seo"],"ecommerce-website":["ui-ux","seo","custom-website"],"custom-website":["ui-ux","corporate-website","seo"],"ui-ux":["custom-website","corporate-website","ecommerce-website"],wordpress:["corporate-website","seo"],seo:["corporate-website","ecommerce-website"]};
export async function generateMetadata({params}:{params:Promise<{service:string}>}):Promise<Metadata>{const {service}=await params;const item=servicePages[service as ServiceSlug];return item?pageMetadata(item.title,item.description,`/services/${service}`):{robots:{index:false,follow:false}}}
export default async function ServicePage({params}:{params:Promise<{service:string}>}){const {service}=await params;const slug=service as ServiceSlug;const item=servicePages[slug];if(!item)notFound();const url=absoluteUrl(`/services/${service}`);const schema={"@context":"https://schema.org","@graph":[{"@type":"Service",name:item.title,description:item.description,url,provider:{"@type":"ProfessionalService",name:"وب‌ساز",url:absoluteUrl("/")}},{"@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"خانه",item:absoluteUrl("/")},{"@type":"ListItem",position:2,name:"خدمات",item:absoluteUrl("/services")},{"@type":"ListItem",position:3,name:item.title,item:url}]}]};return <><Header/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/><main><nav className="container crumb" aria-label="مسیر صفحه"><Link href="/">خانه</Link><span>›</span><Link href="/services">خدمات</Link><span>›</span><span aria-current="page">{item.title}</span></nav><PageHero kicker="خدمات وب‌ساز" title={item.title} text={item.intro}/><section className="section container"><div className="split"><article><h2>این خدمت برای چه کسب‌وکارهایی مناسب است؟</h2><p>{item.audience}</p><h2>خروجی همکاری</h2><ul>{item.deliverables.map(x=><li key={x}>{x}</li>)}</ul></article><article><h2>مزیت‌های این راهکار</h2><ul>{item.benefits.map(x=><li key={x}>{x}</li>)}</ul><p>محدوده دقیق، زمان‌بندی و هزینه پس از بررسی نیازهای واقعی پروژه مشخص می‌شود.</p></article></div></section><section className="section pale"><div className="container"><h2>فرایند اجرای پروژه</h2><div className="steps">{["شناخت نیاز و هدف","طراحی ساختار و رابط","پیاده‌سازی و آزمون","تحویل و پشتیبانی"].map((x,i)=><div key={x}><span>{i+1}</span><b>{x}</b></div>)}</div><div className="actions"><Link className="btn primary" href="/contact">درخواست بررسی پروژه</Link><Link className="btn secondary" href={item.related}>{item.relatedLabel}</Link></div><h2>خدمات مرتبط</h2><div className="actions">{related[slug].map(key=><Link className="text-link" href={`/services/${key}`} key={key}>{servicePages[key].title}</Link>)}</div></div></section></main><Footer/></>}
