import Link from "next/link";
import { notFound } from "next/navigation";
import { Footer, Header, Icon, PageHero, SectionTitle } from "../components";
import { faqs, portfolio, services, testimonials } from "../data";
import { ContactForm } from "../contact-form";

const pages:Record<string,{kicker:string,title:string,text:string}>={
 services:{kicker:"راهکارهای ما",title:"خدمات کامل طراحی و توسعه وب",text:"از استراتژی و طراحی تا اجرا، رشد و پشتیبانی؛ هر آنچه برای حضور قدرتمند آنلاین نیاز دارید."},
 portfolio:{kicker:"داستان‌های موفقیت",title:"نمونه‌کارهای منتخب وب‌ساز",text:"پروژه‌هایی که با شناخت دقیق مسئله، طراحی هدفمند و اجرای باکیفیت ساخته شده‌اند."},
 pricing:{kicker:"سرمایه‌گذاری شفاف",title:"تعرفه‌های طراحی سایت",text:"پلن‌های منعطف برای مرحله‌های مختلف رشد؛ بدون هزینه پنهان و با جزئیات روشن."},
 about:{kicker:"درباره وب‌ساز",title:"یک تیم کوچک با اثرگذاری بزرگ",text:"طراح، توسعه‌دهنده و استراتژیست‌هایی که به رشد واقعی کسب‌وکار شما فکر می‌کنند."},
 blog:{kicker:"مجله وب‌ساز",title:"یاد بگیرید، بهتر تصمیم بگیرید",text:"مقاله‌های کاربردی درباره طراحی محصول، تجربه کاربری، توسعه وب و بازاریابی دیجیتال."},
 contact:{kicker:"شروع همکاری",title:"بیایید درباره پروژه شما صحبت کنیم",text:"اهداف و نیازهای خود را برای ما بنویسید؛ حداکثر تا یک روز کاری با شما تماس می‌گیریم."},
};
export function generateStaticParams(){return Object.keys(pages).map(slug=>({slug}))}
export default async function GeneralPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params; const p=pages[slug]; if(!p)notFound();return <><Header/><main><PageHero {...p}/>{slug==="services"&&<Services/>}{slug==="portfolio"&&<Portfolio/>}{slug==="pricing"&&<Pricing/>}{slug==="about"&&<About/>}{slug==="blog"&&<Blog/>}{slug==="contact"&&<Contact/>}</main><Footer/></>}
function Services(){return <><section className="section container"><div className="detail-grid">{services.map((s,i)=><article id={s.slug} key={s.slug}><div><Icon value={s.icon}/><small>۰{i+1}</small></div><h2>{s.title}</h2><p>{s.short} با تحلیل نیازهای کسب‌وکار، معماری درست و اجرای دقیق، راهکاری می‌سازیم که امروز کارآمد و فردا توسعه‌پذیر باشد.</p><ul><li>طراحی اختصاصی و واکنش‌گرا</li><li>استانداردهای سرعت و دسترس‌پذیری</li><li>آموزش و پشتیبانی پس از تحویل</li></ul><Link href="/contact">دریافت مشاوره ←</Link></article>)}</div></section><Process/></>}
function Portfolio(){return <section className="section container"><div className="filter"><button className="active">همه</button><button>فروشگاهی</button><button>شرکتی</button><button>محصول دیجیتال</button></div><div className="portfolio-grid large">{portfolio.map((p,i)=><article className={`portfolio-card tone-${i%4+1}`} key={p.slug}><div className="browser-shot"><i/><i/><i/><div><b>{p.title}</b><span>{p.category}</span></div></div><div className="case-meta"><div><h3>{p.title}</h3><p>{p.category}</p></div><strong>{p.result}</strong></div></article>)}</div></section>}
function Pricing(){const plans=[{n:"شروع",p:"از ۳۵ میلیون",d:"برای کسب‌وکارهای کوچک",f:["طراحی تا ۵ صفحه","نسخه موبایل","مدیریت محتوا","یک ماه پشتیبانی"]},{n:"رشد",p:"از ۶۵ میلیون",d:"برای برندهای در حال رشد",f:["طراحی تا ۱۲ صفحه","طراحی UI اختصاصی","سئوی فنی و سرعت","سه ماه پشتیبانی"],hot:true},{n:"اختصاصی",p:"شروع از ۱۲۰ میلیون",d:"برای محصولات و سامانه‌ها",f:["تحلیل و معماری محصول","پنل و امکانات سفارشی","اتصال به سرویس‌ها","شش ماه پشتیبانی"]}];return <><section className="section container"><div className="pricing-grid">{plans.map(x=><article className={x.hot?"hot":""} key={x.n}>{x.hot&&<span className="popular">پیشنهاد محبوب</span>}<h2>{x.n}</h2><p>{x.d}</p><strong>{x.p}</strong><ul>{x.f.map(f=><li key={f}>✓ {f}</li>)}</ul><Link className={`btn ${x.hot?"primary":"secondary"}`} href="/contact">شروع گفتگو</Link></article>)}</div></section><Faq/></>}
function About(){return <><section className="section container split about"><div><SectionTitle align="right" kicker="داستان ما" title="طراحی خوب، باید نتیجه بسازد" text="وب‌ساز از یک باور ساده شکل گرفت: وب‌سایت نباید فقط زیبا باشد؛ باید اعتماد ایجاد کند، کار را برای کاربر ساده کند و به رشد کسب‌وکار کمک کند."/><p>از سال ۱۳۹۷ کنار تیم‌های کوچک و برندهای بزرگ ایستاده‌ایم. امروز با ترکیب استراتژی، طراحی و فناوری، محصولاتی می‌سازیم که کار کردن با آن‌ها لذت‌بخش است.</p></div><div className="about-card"><b>+۲۰۰</b><span>پروژه موفق</span><b>+۸</b><span>سال تجربه مستمر</span><b>۱۲</b><span>هم‌تیمی متخصص</span></div></section><section className="section pale"><div className="container"><SectionTitle kicker="ارزش‌های ما" title="چیزی که به آن پایبندیم" text="اصولی که کیفیت همکاری و خروجی ما را تعریف می‌کنند."/><div className="values">{["شفافیت در مسیر و هزینه","مسئولیت‌پذیری تا رسیدن به نتیجه","سادگی در طراحی و ارتباط","یادگیری و بهبود مستمر"].map((x,i)=><div key={x}><Icon value={["◎","✓","◇","↗"][i]}/><h3>{x}</h3></div>)}</div></div></section><section className="section container"><SectionTitle kicker="اعتماد ساخته‌شده" title="مشتریان از همکاری با ما می‌گویند" text="نتیجه خوب، بهترین معرفی ماست."/><div className="testimonial-grid">{testimonials.map(t=><figure key={t.name}><blockquote>«{t.text}»</blockquote><figcaption><b>{t.name}</b><small>{t.role}</small></figcaption></figure>)}</div></section></>}
function Blog(){const posts=["۷ اصل طراحی صفحه اصلی پرفروش","چطور سرعت سایت را دو برابر کنیم؟","راهنمای انتخاب شرکت طراحی سایت","سئو تکنیکال چیست و چرا مهم است؟","طراحی موبایل‌محور به زبان ساده","هزینه واقعی یک وب‌سایت حرفه‌ای"];return <section className="section container"><div className="blog-grid">{posts.map((x,i)=><article key={x}><div className={`post-cover tone-${i%4+1}`}><span>{["UI/UX","سرعت","کسب‌وکار","SEO","موبایل","بودجه"][i]}</span></div><small>۱۲ شهریور ۱۴۰۵ · ۷ دقیقه</small><h2>{x}</h2><p>نکته‌های عملی و تجربه‌شده برای ساخت وب‌سایتی بهتر و تصمیم‌گیری هوشمندانه‌تر.</p><a href="#">مطالعه مقاله ←</a></article>)}</div></section>}
function Contact(){return <section className="section container contact-grid"><ContactForm/><aside className="contact-aside"><h2>مستقیم با ما در ارتباط باشید</h2><p>برای پاسخ سریع‌تر در ساعات کاری، می‌توانید تماس بگیرید یا در واتساپ پیام دهید.</p><div><Icon value="☎"/><span>تلفن تماس<b>۰۲۱-۹۱۰۰۰۰۰۰</b></span></div><div><Icon value="@"/><span>ایمیل<b>hello@websaz.ir</b></span></div><div><Icon value="⌖"/><span>آدرس<b>تهران، میدان ونک</b></span></div><div className="hours"><b>ساعات پاسخ‌گویی</b><span>شنبه تا چهارشنبه: ۹ تا ۱۸</span><span>پنجشنبه: ۹ تا ۱۴</span></div></aside></section>}
function Process(){return <section className="section pale"><div className="container"><SectionTitle kicker="مسیر همکاری" title="یک فرآیند شفاف از شروع تا تحویل" text="شما در تمام مسیر، دید کامل و امکان بازخورد دارید."/><div className="steps">{["جلسه کشف","برنامه‌ریزی","طراحی","توسعه","راه‌اندازی"].map((x,i)=><div key={x}><span>{i+1}</span><b>{x}</b></div>)}</div></div></section>}
function Faq(){return <section className="section faq-wrap"><div className="container faq-grid"><div><span className="eyebrow">سؤالات متداول</span><h2>قبل از شروع بدانید</h2></div><div>{faqs.map(f=><details key={f.q}><summary>{f.q}<span>+</span></summary><p>{f.a}</p></details>)}</div></div></section>}
